### ISSUE TITLE
Some SI-UBL 1.2 error files are valid

### ISSUE THREAD

**Issue by ThijsFTW** [peppolautoriteit-nl/testset#10]
Some files in the SI-UBL 1.2 directory that are marked as 'error' are actually valid. When validating against the online test tool they are validated as valid: https://ecosio.com/en/peppol-and-xml-document-validator/. 

Tested and validated as SimplerInvoicing Order 1.2.3 or SimplerInvoicing Invoice 1.2.3, depending on the type of invoice.
The following files are incorrectly marked as 'error':

SI-UBL-INV-1.2-error-CL-T10-R003.xml
SI-UBL-INV-1.2-error-CL-T10-R008.xml
SI-UBL-INV-1.2-error-CODE-R004.xml
SI-UBL-INV-1.2-error-OP-T10-R002.xml
SI-UBL-INV-1.2-error-OP-T10-R003.xml
SI-UBL-INV-1.2-error-OP-T10-R004.xml
SI-UBL-INV-1.2-error-OP-T10-R006.xml
SI-UBL-INV-1.2-error-OP-T10-R008.xml
SI-UBL-INV-1.2-error-SI-INV-R025.xml
SI-UBL-PO-1.2-error-BII2-T01-R015.xml
SI-UBL-PO-1.2-error-SI-V12-PO-R200.xml

**Comment by tjeb** [comment]
The last two did indeed not fail, fixed in a7c36413a2820feb7f49189566a3c3d9b1701011

However, all the other ones are correct (in that they should fail validation). I'm not quite sure why the ecosio validator isn't catching the errors, but you can see on https://peppol-test.nl/validate that they fail validation

**Comment by ThijsFTW** [comment]
Thanks. I passed it to phax/phive-rules. Seems like there is a bug there. That software is also used for the ecosio validator.
https://github.com/phax/phive-rules/issues/9
