### ISSUE TITLE
Some examples do not return expected output - Part 2

### ISSUE THREAD

**Issue by ojundt** [peppolautoriteit-nl/testset#7]
Hi, I just ran the most recent version of the testset (34d865a8) against the most recent version of the validation files (0f5f0632) and unfortunately there are still some issues:

`SI-UBL-2.0_BR-NL-8_ok_381.xml` should be valid but returns:
```
12:0: ERROR: Element '{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}CreditNoteTypeCode': This element is not expected. Expected is one of ( {urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}IssueTime, {urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxPointDate, {urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}Note, {urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}DocumentCurrencyCode, {urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxCurrencyCode, {urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}PricingCurrencyCode, {urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}PaymentCurrencyCode, {urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}PaymentAlternativeCurrencyCode, {urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}AccountingCostCode, {urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}AccountingCost ).
```

`SI-UBL-INV-1.2-warning-CL-T10-R006.xml` should be valid with warning but returns fatal error `[CL-T10-R006]-Payment means in an invoice MUST be coded using UNCL 4461 BII2 subset`

`SI-UBL-INV-1.2-warning-CL-T10-R007.xml` should be valid with warning but returns fatal error `[CL-T10-R007]-Invoice tax categories MUST be coded using UNCL 5305 code list BII2 subset`

`SI-UBL-1.1-ok-single-item.xml` should be valid but returns `[SI-V11-INV-R200]-This XML instance is NOT tagged as an SI-UBL 1.1 invoice; please check the CustomizationID value`

Can you confirm?

**Comment by jdiepenmaat** [comment]
@tjeb I reckon it's time for some CI testing on this project, what do you think?

**Comment by tjeb** [comment]
For the first one, please note that it's a CreditNote, not an Invoice; you are getting an xml schema error (probably because you are xsd-validating it against an Invoice).

I have removed the two 1.2 warning files; they already had error equivalents but somehow i managed to not remove them from the repo.

Fixed CustomizationID in the 1.1 file, though honestly I am considering removing all of the 1.1 files now that they are obsolete.

Changes in commit dc87ecc

**Comment by tjeb** [comment]
@jdiepenmaat slowly getting there :) (but time is limited and priorities tend to lie elsewhere). Am considering merging the validation repository with the testset, which should make ci a tad easier to implement.

**Comment by ojundt** [comment]
Thanks for updating the testset so quickly. 

+1 for merging the `validation` and `testset` repository.

Regarding `SI-UBL-2.0_BR-NL-8_ok_381.xml`: `si-ubl-2.0.1.xsl` also contains `CreditNote` checks so I assume it should be useable for validating both, `Invoice` and `CreditNote` documents, correct?

**Comment by tjeb** [comment]
Yes, it should be usable for both, but that error you see is not from the xsl, but from an xsd check (for UBL 2.1, one of https://docs.oasis-open.org/ubl/os-UBL-2.1/xsd/maindoc/ depending on the document type), in this case either UBL-Invoice-2.1.xsd or UBL-CreditNote-2.1.xsd.

Now that I look at the error you get again, it looks like your validator does correctly validate against a CreditNote xsd file, but I suspect for UBL 2.0 instead of UBL 2.1.

**Comment by ojundt** [comment]
That was it! I oversaw the part where we are validating against xsd first and it was UBL 2.0. That closes this issue for me.
